services:
  - type: web
    plan: free
    name: Quiz Time
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn capstone.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
